### PR TITLE
Add support for Copernicus

### PR DESCRIPTION
**Pull request by nuest**
Working on my Open Science karma this week, so here's support for another publisher: Copernicus.

If you don't like the `...` exposed in `suppdata(..)` then I'm happy to revert that change. Feedback welcome.

Implements a part of #2.

### CODE REVIEW

**Comment by nuest** [comment]
And here's a GIF for the Tweet if accepted :-)

copernicus-suppdata

**Comment by willpearse** [comment]
Your karma has certainly made it a good week for `suppdata`: thank you!!! It's always nice to receive such well-written PRs that contain unit tests. I'm also _incredibly_ grateful that you've gone through and neatened up the docs - getting that last 2% finished is the hardest bit, and it's great to see you doing such a good job of it.

Three quick questions before I can accept this:
1. Is it the case that Copernicus journals _never_ have more than one supplement, and it is _always_ a zip file if there is one? What you have written is excellent if so, but if not then we'll need to change it a little.
2. I'm not averse to cascading `...` through, but could you tell me why you've done it? I quite like functions to complain if they're given arguments they don't expect; I'm happy to have that stop, but I'd like to know what the feature is this gives.
3. This is the second non-trivial code contribution you've made to the package, alongside a number of 'quality of life' improvements. I'm really grateful for all the effort you've put in, and would like you to have something as a reward (beyond karma :D). Citations and co-authorship are how we get "paid" in academia, so: would you like to be an 'author' on the package? If so, go ahead and make yourself one inbetween me and Scott in the `DESCRIPTION` (follow his example here: https://github.com/ropensci/suppdata/blob/master/DESCRIPTION#L6)

**Comment by nuest** [comment]
Re 1: I reached out to my contact at Copernicus to make sure

Re 2: It gives me the possibility to "forward" the `unzip.after.download` parameter down to the `.suppdata.copernicus(..)` function to control unzipping. Given we get a positive answer for question 1, would you be fine with a default to always unzip the downloaded archive? Then we could remove the `...` again. If provider-specific parameters come up again, you could revisit it.

Re 3: It would an honour and you just made my day! I will update the PR. Thanks!

**Comment by nuest** [comment]
Update Re 1: https://publications.copernicus.org/for_authors/manuscript_preparation.html says:

> Supplements will receive their own DOI (digital object identifier) and will be published online along with the article as *.zip archive or single *.pdf file.

I will look for an example where the supplement is a PDF file, and test with that. 

What is your preference regarding unzipping or not if the whole supplement archive is downloaded? Always unzip, or never unzip? If we choose either, then I could remove the `...` again.

**Comment by willpearse** [comment]
1. Brilliant, thanks for looking this up.

2. I've quickly looked at the site and, currently, it looks like all the zip files have filenames that are something like `last-part-of-doi.zip`. So, for example, article _10.5194/bg-14-1739-2017_ has a supplement called `bg-14-1739-2017-supplement.zip` - it looks to be derived from `journalname-volume-firstpage-supplement.zip`. So, if this is a general pattern, then we have a solution: if the file the user asks for is the name of the supplement zip file, don't unzip it, and (presumably) the same for the PDF. If this turns out to be difficult to do, I'm happy to always unzip.
I would prefer to avoid adding extra arguments and/or cascading `...` through if we can. This has caused me pain in other packages; it all seems simple now, but in two years time when neither of us can remember what's going on in the package this sort of thing becomes magic code.

3. Glad you're pleased, but the honour is all mine. Thank you for being so helpful!

**Comment by nuest** [comment]
Apologies for the delay, will get to this tomorrow.

**Comment by willpearse** [comment]
No rush my end; please don't apologise! I won't be able to look at this until Monday anyway.

**Comment by nuest** [comment]
I removed the `...` argument and implemented the discussed behaviour for unzipping, although it is not needed to give the pdf file name, because I don't want to confuse potential pdf files within the archive.
Tests updated, too, to show the new behaviour.

**Comment by willpearse** [comment]
All looks fantastic. Thanks again for your help with this, Daniel!

**Pull request merged**
